-- Add creditCardToken column to subscriptions table
-- This token is generated by ASAAS tokenization and allows reactivation
-- without requiring the client to re-enter full card data.
-- Safe to run multiple times (IF NOT EXISTS).

ALTER TABLE subscriptions
ADD COLUMN IF NOT EXISTS "creditCardToken" TEXT;

COMMENT ON COLUMN subscriptions."creditCardToken" IS 'Asaas tokenized credit card for reactivation without re-entering card data';
