// Vercel Serverless Function — serves a dynamic Web App Manifest
// by fetching PWA settings from Supabase at request time.
// This replaces the static manifest.webmanifest generated by VitePWA,
// ensuring iOS Safari always gets the correct name/icon/colors.

const SUPABASE_URL = 'https://enjyflztvyomrlzddavk.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuanlmbHp0dnlvbXJsemRkYXZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4OTE2MDksImV4cCI6MjA4NzQ2NzYwOX0.Md-ad9U6vK-OtNg3iUBX-SKCSNdOCppBasgC4ys-STc';
const ICON_BASE = 'https://enjyflztvyomrlzddavk.supabase.co/storage/v1/object/public/avatars/public';

export default async function handler(req, res) {
  try {
    const response = await fetch(
      `${SUPABASE_URL}/rest/v1/store_settings?key=in.(pwa_store_name,pwa_store_short_name,store_name,pwa_store_theme_color,pwa_store_bg_color,pwa_store_icon)&select=key,value`,
      {
        headers: {
          'apikey': SUPABASE_ANON_KEY,
          'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
        },
      }
    );

    const data = await response.json();
    const s = {};
    for (const item of data) {
      if (item.value) s[item.key] = item.value;
    }

    const defaultIcons = [
      { src: `${ICON_BASE}/pwa_icon_192.png`, sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: `${ICON_BASE}/pwa_icon_512.png`, sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: `${ICON_BASE}/pwa_icon_maskable_192.png`, sizes: '192x192', type: 'image/png', purpose: 'maskable' },
      { src: `${ICON_BASE}/pwa_icon_maskable_512.png`, sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ];

    const manifest = {
      name: s.pwa_store_name || s.store_name || 'VINNX BARBER',
      short_name: s.pwa_store_short_name || s.store_name || 'VINNX',
      description: 'Agende seu horário na melhor barbearia',
      start_url: '/#/site',
      scope: '/',
      display: 'standalone',
      background_color: s.pwa_store_bg_color || '#0f172a',
      theme_color: s.pwa_store_theme_color || '#10b981',
      orientation: 'portrait-primary',
      icons: s.pwa_store_icon
        ? [
            { src: s.pwa_store_icon, sizes: '512x512', type: 'image/png' },
            { src: s.pwa_store_icon, sizes: '512x512', type: 'image/png', purpose: 'maskable' },
          ]
        : defaultIcons,
      categories: ['business', 'productivity'],
    };

    res.setHeader('Content-Type', 'application/manifest+json');
    res.setHeader('Cache-Control', 'public, s-maxage=300, stale-while-revalidate=600');
    res.status(200).json(manifest);
  } catch (err) {
    // Fallback static manifest if Supabase is unreachable
    res.setHeader('Content-Type', 'application/manifest+json');
    res.status(200).json({
      name: 'VINNX BARBER',
      short_name: 'VINNX',
      description: 'Agende seu horário na melhor barbearia',
      start_url: '/#/site',
      scope: '/',
      display: 'standalone',
      background_color: '#0f172a',
      theme_color: '#10b981',
      orientation: 'portrait-primary',
      icons: [
        { src: `${ICON_BASE}/pwa_icon_192.png`, sizes: '192x192', type: 'image/png', purpose: 'any' },
        { src: `${ICON_BASE}/pwa_icon_512.png`, sizes: '512x512', type: 'image/png', purpose: 'any' },
      ],
    });
  }
}
